### ISSUE TITLE
Pre-Competition Software and OS Dev Checklist

### ISSUE THREAD

**Issue by sah4jpatel** [BUZZ-Blimps/CatchingBlimp#49]
Tasks at a glance:

- [ ] Get Ubuntu server on all the opis
     - [ ] Test a Pi with it, make sure everything works
- [ ] Develop scripts to quickly clear and push full package to Pis
     - [ ] Create a dev-only testbench OPi that that will push out the package to main Pis
- [ ] Benchmark performance of full blimp operating on Pi
- [ ] Develop Model Training Suite 
     - [ ] Label Studio -> Albumentations -> Yolov10 training -> ONXX2RKNN conversion
     - [ ] Model validation tool for testbench to visualize detections and disparity
